name: continuous

on: [push]

jobs:
  windows-latest:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
         fetch-depth: 0
      - name: Install build tools
        run: |
            Write-Host "Installing VS 2026 Build Tools..."
            choco install visualstudio2026buildtools `
               --package-parameters " --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --includeRecommended --quiet" `
               -y --ignore-package-exit-codes=3010
            Write-Host "VS 2026 Build Tools installation completed" 
            Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
               & $env:temp\dotnet-install.ps1 -Architecture x64 -Version '10.0.100' -InstallDir "$env:ProgramFiles\dotnet"
            winget install Microsoft.DotNet.SDK.10
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3
        with:
          vs-version: '[18.0,)'
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Run: Pack'
        shell: pwsh
        run: ./build.ps1 Pack
